"""Uso de Mapped y mapped_column en los modelos, ademas de la relacion entre rating y review

Revision ID: 06f322943b5b
Revises: af3907f0f541
Create Date: 2025-09-28 19:46:18.561180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06f322943b5b'
down_revision: Union[str, None] = 'af3907f0f541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('reviews', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'reviews', ['rating_id'])
    op.create_foreign_key(None, 'reviews', 'ratings', ['rating_id'], ['rating_id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.alter_column('reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('reviews', 'rating_id')
    op.alter_column('games', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
