"""creacion de la v1 de los modelos Game y Review

Revision ID: 090998e1384b
Revises: f61a27aeb94e
Create Date: 2025-05-18 17:52:51.535946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '090998e1384b'
down_revision: Union[str, None] = 'f61a27aeb94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rawg_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('slug', sa.String(length=200), nullable=False))
    op.add_column('games', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('games', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('games', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=False)
    op.create_unique_constraint(None, 'games', ['rawg_id'])
    op.drop_column('games', 'cover_image')
    op.drop_column('games', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('cover_image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.alter_column('games', 'release_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('games', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('games', 'image_url')
    op.drop_column('games', 'slug')
    op.drop_column('games', 'rawg_id')
    # ### end Alembic commands ###
