"""creacion de modelos rating, developer, publisher y modificacion de otros modelos

Revision ID: 41210b890182
Revises: 5f3b6073497f
Create Date: 2025-05-28 10:21:56.311858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41210b890182'
down_revision: Union[str, None] = '5f3b6073497f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('rawg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('developer_id'),
    sa.UniqueConstraint('rawg_id')
    )
    op.create_table('publishers',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('rawg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    sa.UniqueConstraint('rawg_id')
    )
    op.create_table('developers_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.developer_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'developer_id')
    )
    op.create_table('publishers_association',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'publisher_id')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='cc_score_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game_rating')
    )
    op.drop_column('games', 'review_count')
    op.drop_column('games', 'avg_rating')
    op.drop_column('games', 'developer')
    op.drop_column('games', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('publisher', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('developer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('ratings')
    op.drop_table('publishers_association')
    op.drop_table('developers_association')
    op.drop_table('publishers')
    op.drop_table('developers')
    # ### end Alembic commands ###
