"""Se agregaron los dos campos de la foto de perfil en el modelo del usuario

Revision ID: 5d9fa755be27
Revises: bd9ffa3d49f2
Create Date: 2025-10-29 19:57:53.533352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9fa755be27'
down_revision: Union[str, None] = 'bd9ffa3d49f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_photo_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo_public_id')
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###
