"""Unique Contraint has been added to the WishlistItem model.

Revision ID: 6732600f4543
Revises: 1f8c495e1fc6
Create Date: 2025-11-15 11:16:07.648961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6732600f4543'
down_revision: Union[str, None] = '1f8c495e1fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_game_wishlist_item', 'wishlist_items', ['user_id', 'game_id'])
    op.create_unique_constraint(None, 'wishlist_items', ['wishlist_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_items', type_='unique')
    op.drop_constraint('uq_user_game_wishlist_item', 'wishlist_items', type_='unique')
    # ### end Alembic commands ###
