"""se cambio el nombre de las columnass photo_profile del usuario por avatar

Revision ID: dab990f42f27
Revises: 5d9fa755be27
Create Date: 2025-10-30 19:47:06.576895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab990f42f27'
down_revision: Union[str, None] = '5d9fa755be27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_public_id', sa.String(), nullable=True))
    op.drop_column('users', 'profile_photo_public_id')
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_photo_public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_public_id')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
