"""drop user's columns name, lastname and age

Revision ID: dc6bfd998e59
Revises: 458193b4697f
Create Date: 2025-12-17 14:08:20.295451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc6bfd998e59'
down_revision: Union[str, None] = '458193b4697f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('age', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_table('likes',
    sa.Column('like_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], name=op.f('likes_review_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('like_id', name=op.f('likes_pkey')),
    sa.UniqueConstraint('user_id', 'review_id', name=op.f('uq_user_review_like'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
